name: easy_stepper

description: A fully customizable, beautiful and easy to use stepper widget. It help you to show or collect information from users using organized steps.

version: 0.3.1

homepage: https://github.com/ma7moud3osman
repository: https://github.com/ma7moud3osman/easy_stepper.git
issue_tracker: https://github.com/ma7moud3osman/easy_stepper/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies: 
  flutter:
    sdk: flutter
  lottie: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
